In [326]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import MaxAbsScaler
from sklearn.model_selection import cross_val_score

import joblib
%matplotlib inline

In [347]:
df_1= pd.read_csv('a1_raw.csv')
df_2= pd.read_csv('a1_va3.csv')
df_3=pd.read_csv('a2_raw.csv')
df_4= pd.read_csv('a3_raw.csv')
df_5= pd.read_csv('a3_va3.csv')
df_6=pd.read_csv('b1_raw.csv')
df_7= pd.read_csv('b1_va3.csv')
df_8=pd.read_csv('b3_raw.csv')
df_9= pd.read_csv('b3_va3.csv')
df_10=pd.read_csv('c1_raw.csv')
df_11= pd.read_csv('c1_va3.csv')
df_12=pd.read_csv('c3_raw.csv')
df_13= pd.read_csv('c3_va3.csv')
new_testing_data=pd.read_csv('test.csv')

sample_sub_df=pd.read_csv("sample_submission.csv")

In [346]:
new_testing_data

,1,2,3,4,5,6,7,8,9,10,...,23,24,25,26,27,28,29,30,31,32
0,0.000005,-0.001857,0.000168,0.000131,-0.000346,0.000133,-0.001732,-0.001807,0.000532,-0.000080,...,0.000411,0.000087,0.001864,0.000393,0.002559,0.000221,0.000437,0.000854,0.000456,0.000438
1,-0.000315,-0.001373,0.000267,-0.001972,0.003837,-0.000523,-0.001306,-0.001276,0.000491,-0.000075,...,0.000117,-0.000162,0.001434,0.004345,0.001891,0.000464,0.000184,0.001477,0.000213,0.000200
2,-0.000062,0.000436,0.000166,0.001393,-0.000442,0.000208,0.000978,0.000517,-0.000007,-0.000097,...,0.000609,0.000129,0.000471,0.001476,0.001106,0.002402,0.000538,0.001615,0.000867,0.000622
3,0.000727,0.001626,0.000234,-0.000131,0.000611,-0.000129,0.001150,0.001554,-0.000068,0.000364,...,-0.001062,-0.000085,0.001796,0.000638,0.001935,0.000375,0.000621,0.000818,0.000458,0.001084
4,0.000675,0.000493,0.000179,0.001253,-0.002160,0.000288,0.000606,0.000395,-0.000015,0.001053,...,-0.000499,0.000121,0.000854,0.002514,0.000724,0.001933,0.000366,0.001008,0.000413,0.000560
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1255,-0.000205,-0.011925,-0.001228,-0.000068,-0.009515,-0.000888,-0.006188,-0.001810,-0.001355,-0.000769,...,0.000026,0.000028,0.011990,0.009556,0.006589,0.005133,0.000948,0.000705,0.000203,0.000102
1256,-0.000512,-0.008675,-0.000836,0.000104,-0.006742,-0.000619,-0.007582,-0.007929,-0.000503,-0.001528,...,-0.000277,0.000108,0.008730,0.006771,0.010982,0.006924,0.000522,0.000443,0.001005,0.000321
1257,-0.000679,-0.005859,-0.000635,0.000279,-0.006121,-0.000282,-0.003322,-0.006726,-0.000052,-0.001570,...,0.000182,-0.000008,0.005933,0.006133,0.007502,0.005719,0.000410,0.000105,0.000645,0.000182
1258,-0.001319,-0.004339,-0.000651,0.000340,-0.004804,-0.000550,-0.003313,-0.006431,0.000018,-0.000515,...,0.000111,-0.000043,0.004582,0.004847,0.007234,0.005123,0.000446,0.000364,0.000082,0.000309
1259,-0.002218,-0.004341,-0.000970,0.001161,-0.005571,-0.000675,-0.001380,-0.002071,-0.000061,0.000729,...,0.001133,-0.000258,0.004970,0.005730,0.002489,0.003343,0.000561,0.000665,0.002806,0.001374

In [328]:

df_2.shape

df_5.shape

df_7.shape

df_9.shape

df_11.shape

df_13.shape
new_testing_data.shape

(1260, 32)

In [329]:

df_2.info()

df_5.info()

df_7.info()

df_9.info()

df_11.info()

df_13.info()
new_testing_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1743 entries, 0 to 1742
Data columns (total 33 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1       1743 non-null   float64
 1   2       1743 non-null   float64
 2   3       1743 non-null   float64
 3   4       1743 non-null   float64
 4   5       1743 non-null   float64
 5   6       1743 non-null   float64
 6   7       1743 non-null   float64
 7   8       1743 non-null   float64
 8   9       1743 non-null   float64
 9   10      1743 non-null   float64
 10  11      1743 non-null   float64
 11  12      1743 non-null   float64
 12  13      1743 non-null   float64
 13  14      1743 non-null   float64
 14  15      1743 non-null   float64
 15  16      1743 non-null   float64
 16  17      1743 non-null   float64
 17  18      1743 non-null   float64
 18  19      1743 non-null   float64
 19  20      1743 non-null   float64
 20  21      1743 non-null   float64
 21  22      1743 non-null   float64
 22  23      1743 non-null   float64
 23  24      1743 non-null   float64
 24  25      1743 non-null   float64
 25  26      1743 non-null   float64
 26  27      1743 non-null   float64
 27  28      1743 non-null   float64
 28  29      1743 non-null   float64
 29  30      1743 non-null   float64
 30  31      1743 non-null   float64
 31  32      1743 non-null   float64
 32  Phase   1743 non-null   object
dtypes: float64(32), object(1)
memory usage: 449.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1830 entries, 0 to 1829
Data columns (total 33 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1       1830 non-null   float64
 1   2       1830 non-null   float64
 2   3       1830 non-null   float64
 3   4       1830 non-null   float64
 4   5       1830 non-null   float64
 5   6       1830 non-null   float64
 6   7       1830 non-null   float64
 7   8       1830 non-null   float64
 8   9       1830 non-null   float64
 9   10      1830 non-null   float64
 10  11      1830 non-null   float64
 11  12      1830 non-null   float64
 12  13      1830 non-null   float64
 13  14      1830 non-null   float64
 14  15      1830 non-null   float64
 15  16      1830 non-null   float64
 16  17      1830 non-null   float64
 17  18      1830 non-null   float64
 18  19      1830 non-null   float64
 19  20      1830 non-null   float64
 20  21      1830 non-null   float64
 21  22      1830 non-null   float64
 22  23      1830 non-null   float64
 23  24      1830 non-null   float64
 24  25      1830 non-null   float64
 25  26      1830 non-null   float64
 26  27      1830 non-null   float64
 27  28      1830 non-null   float64
 28  29      1830 non-null   float64
 29  30      1830 non-null   float64
 30  31      1830 non-null   float64
 31  32      1830 non-null   float64
 32  Phase   1830 non-null   object
dtypes: float64(32), object(1)
memory usage: 471.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1069 entries, 0 to 1068
Data columns (total 33 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1       1069 non-null   float64
 1   2       1069 non-null   float64
 2   3       1069 non-null   float64
 3   4       1069 non-null   float64
 4   5       1069 non-null   float64
 5   6       1069 non-null   float64
 6   7       1069 non-null   float64
 7   8       1069 non-null   float64
 8   9       1069 non-null   float64
 9   10      1069 non-null   float64
 10  11      1069 non-null   float64
 11  12      1069 non-null   float64
 12  13      1069 non-null   float64
 13  14      1069 non-null   float64
 14  15      1069 non-null   float64
 15  16      1069 non-null   float64
 16  17      1069 non-null   float64
 17  18      1069 non-null   float64
 18  19      1069 non-null   float64
 19  20      1069 non-null   float64
 20  21      1069 non-null   float64
 21  22      1069 non-null   float64
 22  23      1069 non-null   float64
 23  24      1069 non-null   float64
 24  25      1069 non-null   float64
 25  26      1069 non-null   float64
 26  27      1069 non-null   float64
 27  28      1069 non-null   float64
 28  29      1069 non-null   float64
 29  30      1069 non-null   float64
 30  31      1069 non-null   float64
 31  32      1069 non-null   float64
 32  Phase   1069 non-null   object
dtypes: float64(32), object(1)
memory usage: 275.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1420 entries, 0 to 1419
Data columns (total 33 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1       1420 non-null   float64
 1   2       1420 non-null   float64
 2   3       1420 non-null   float64
 3   4       1420 non-null   float64
 4   5       1420 non-null   float64
 5   6       1420 non-null   float64
 6   7       1420 non-null   float64
 7   8       1420 non-null   float64
 8   9       1420 non-null   float64
 9   10      1420 non-null   float64
 10  11      1420 non-null   float64
 11  12      1420 non-null   float64
 12  13      1420 non-null   float64
 13  14      1420 non-null   float64
 14  15      1420 non-null   float64
 15  16      1420 non-null   float64
 16  17      1420 non-null   float64
 17  18      1420 non-null   float64
 18  19      1420 non-null   float64
 19  20      1420 non-null   float64
 20  21      1420 non-null   float64
 21  22      1420 non-null   float64
 22  23      1420 non-null   float64
 23  24      1420 non-null   float64
 24  25      1420 non-null   float64
 25  26      1420 non-null   float64
 26  27      1420 non-null   float64
 27  28      1420 non-null   float64
 28  29      1420 non-null   float64
 29  30      1420 non-null   float64
 30  31      1420 non-null   float64
 31  32      1420 non-null   float64
 32  Phase   1420 non-null   object
dtypes: float64(32), object(1)
memory usage: 366.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1107 entries, 0 to 1106
Data columns (total 33 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1       1107 non-null   float64
 1   2       1107 non-null   float64
 2   3       1107 non-null   float64
 3   4       1107 non-null   float64
 4   5       1107 non-null   float64
 5   6       1107 non-null   float64
 6   7       1107 non-null   float64
 7   8       1107 non-null   float64
 8   9       1107 non-null   float64
 9   10      1107 non-null   float64
 10  11      1107 non-null   float64
 11  12      1107 non-null   float64
 12  13      1107 non-null   float64
 13  14      1107 non-null   float64
 14  15      1107 non-null   float64
 15  16      1107 non-null   float64
 16  17      1107 non-null   float64
 17  18      1107 non-null   float64
 18  19      1107 non-null   float64
 19  20      1107 non-null   float64
 20  21      1107 non-null   float64
 21  22      1107 non-null   float64
 22  23      1107 non-null   float64
 23  24      1107 non-null   float64
 24  25      1107 non-null   float64
 25  26      1107 non-null   float64
 26  27      1107 non-null   float64
 27  28      1107 non-null   float64
 28  29      1107 non-null   float64
 29  30      1107 non-null   float64
 30  31      1107 non-null   float64
 31  32      1107 non-null   float64
 32  Phase   1107 non-null   object
dtypes: float64(32), object(1)
memory usage: 285.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1444 entries, 0 to 1443
Data columns (total 33 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1       1444 non-null   float64
 1   2       1444 non-null   float64
 2   3       1444 non-null   float64
 3   4       1444 non-null   float64
 4   5       1444 non-null   float64
 5   6       1444 non-null   float64
 6   7       1444 non-null   float64
 7   8       1444 non-null   float64
 8   9       1444 non-null   float64
 9   10      1444 non-null   float64
 10  11      1444 non-null   float64
 11  12      1444 non-null   float64
 12  13      1444 non-null   float64
 13  14      1444 non-null   float64
 14  15      1444 non-null   float64
 15  16      1444 non-null   float64
 16  17      1444 non-null   float64
 17  18      1444 non-null   float64
 18  19      1444 non-null   float64
 19  20      1444 non-null   float64
 20  21      1444 non-null   float64
 21  22      1444 non-null   float64
 22  23      1444 non-null   float64
 23  24      1444 non-null   float64
 24  25      1444 non-null   float64
 25  26      1444 non-null   float64
 26  27      1444 non-null   float64
 27  28      1444 non-null   float64
 28  29      1444 non-null   float64
 29  30      1444 non-null   float64
 30  31      1444 non-null   float64
 31  32      1444 non-null   float64
 32  Phase   1444 non-null   object
dtypes: float64(32), object(1)
memory usage: 372.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1260 entries, 0 to 1259
Data columns (total 32 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1       1260 non-null   float64
 1   2       1260 non-null   float64
 2   3       1260 non-null   float64
 3   4       1260 non-null   float64
 4   5       1260 non-null   float64
 5   6       1260 non-null   float64
 6   7       1260 non-null   float64
 7   8       1260 non-null   float64
 8   9       1260 non-null   float64
 9   10      1260 non-null   float64
 10  11      1260 non-null   float64
 11  12      1260 non-null   float64
 12  13      1260 non-null   float64
 13  14      1260 non-null   float64
 14  15      1260 non-null   float64
 15  16      1260 non-null   float64
 16  17      1260 non-null   float64
 17  18      1260 non-null   float64
 18  19      1260 non-null   float64
 19  20      1260 non-null   float64
 20  21      1260 non-null   float64
 21  22      1260 non-null   float64
 22  23      1260 non-null   float64
 23  24      1260 non-null   float64
 24  25      1260 non-null   float64
 25  26      1260 non-null   float64
 26  27      1260 non-null   float64
 27  28      1260 non-null   float64
 28  29      1260 non-null   float64
 29  30      1260 non-null   float64
 30  31      1260 non-null   float64
 31  32      1260 non-null   float64
dtypes: float64(32)
memory usage: 315.1 KB

In [334]:
df_9.isnull().any()

1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
30       False
31       False
32       False
Phase    False
dtype: bool

In [310]:
df_2

,1,2,3,4,5,6,7,8,9,10,...,24,25,26,27,28,29,30,31,32,Phase
0,-0.005009,-0.000964,0.000573,0.008623,0.005667,0.001302,-0.000631,0.000130,-0.000048,0.007762,...,1.880800e-04,0.005133,0.010400,0.000646,0.007871,0.004631,0.000963,0.000092,0.000438,D
1,0.004905,0.001209,-0.000649,0.004737,0.003166,0.000819,-0.000572,-0.000015,0.000023,0.002706,...,-7.500000e-07,0.005093,0.005756,0.000573,0.003459,0.000730,0.000332,0.000012,0.000433,D
2,-0.002393,-0.000216,0.000136,0.003028,0.001212,0.000336,-0.000449,0.000017,0.000047,0.002868,...,-3.920000e-05,0.002406,0.003279,0.000452,0.003261,0.002412,0.000852,0.000042,0.000202,D
3,-0.001394,-0.000242,0.000056,0.001182,0.000575,0.000225,-0.000479,-0.000050,0.000104,0.001171,...,-3.184000e-05,0.001416,0.001334,0.000493,0.001358,0.000313,0.000611,0.000029,0.000596,D
4,-0.000156,-0.000004,0.000023,0.001585,0.000630,0.000094,-0.000303,0.000097,0.000065,0.001579,...,-2.015000e-05,0.000158,0.001709,0.000325,0.001713,0.000203,0.000069,0.000038,0.000069,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1738,0.001042,0.000111,-0.000199,-0.009265,0.002095,-0.000616,0.001041,0.000117,-0.000199,-0.000098,...,7.890000e-05,0.001067,0.009519,0.001066,0.000232,0.000015,0.000210,0.000016,0.000308,D
1739,0.000883,0.000107,-0.000172,0.013037,-0.001307,0.000705,0.000881,0.000115,-0.000172,0.001688,...,2.084600e-04,0.000906,0.013122,0.000905,0.001851,0.000052,0.007290,0.000052,0.000623,D
1740,-0.000141,-0.000053,0.000007,0.011722,-0.000576,0.000647,-0.000143,-0.000045,0.000007,0.001912,...,-1.458000e-05,0.000151,0.011754,0.000150,0.002075,0.000339,0.000486,0.000339,0.000081,D
1741,-0.000043,-0.000060,-0.000004,0.009195,-0.000926,0.000624,-0.000043,-0.000059,-0.000004,0.001912,...,-2.543000e-05,0.000074,0.009262,0.000073,0.001950,0.000016,0.000411,0.000016,0.000136,D
1742,-0.000209,-0.000072,0.000028,-0.009025,0.000814,-0.000505,-0.000208,-0.000073,0.000028,-0.000149,...,-1.289500e-04,0.000223,0.009076,0.000223,0.000366,0.000045,0.004826,0.000044,0.000558,D

In [311]:
df_2.head()

,1,2,3,4,5,6,7,8,9,10,...,24,25,26,27,28,29,30,31,32,Phase
0,-0.005009,-0.000964,0.000573,0.008623,0.005667,0.001302,-0.000631,0.000130,-0.000048,0.007762,...,1.880800e-04,0.005133,0.010400,0.000646,0.007871,0.004631,0.000963,0.000092,0.000438,D
1,0.004905,0.001209,-0.000649,0.004737,0.003166,0.000819,-0.000572,-0.000015,0.000023,0.002706,...,-7.500000e-07,0.005093,0.005756,0.000573,0.003459,0.000730,0.000332,0.000012,0.000433,D
2,-0.002393,-0.000216,0.000136,0.003028,0.001212,0.000336,-0.000449,0.000017,0.000047,0.002868,...,-3.920000e-05,0.002406,0.003279,0.000452,0.003261,0.002412,0.000852,0.000042,0.000202,D
3,-0.001394,-0.000242,0.000056,0.001182,0.000575,0.000225,-0.000479,-0.000050,0.000104,0.001171,...,-3.184000e-05,0.001416,0.001334,0.000493,0.001358,0.000313,0.000611,0.000029,0.000596,D
4,-0.000156,-0.000004,0.000023,0.001585,0.000630,0.000094,-0.000303,0.000097,0.000065,0.001579,...,-2.015000e-05,0.000158,0.001709,0.000325,0.001713,0.000203,0.000069,0.000038,0.000069,D

In [312]:
print(df_2.describe())

                 1            2            3            4            5  \
count  1743.000000  1743.000000  1743.000000  1743.000000  1743.000000
mean      0.000043    -0.000038     0.000009    -0.000096    -0.000016
std       0.009486     0.013221     0.001706     0.011605     0.013800
min      -0.072620    -0.064095    -0.010349    -0.095705    -0.061352
25%      -0.001614    -0.001834    -0.000309    -0.002472    -0.003462
50%      -0.000031     0.000022     0.000003     0.000073     0.000053
75%       0.001580     0.001663     0.000225     0.003612     0.003093
max       0.073446     0.071600     0.010463     0.046461     0.132058

                 6            7             8            9           10  ...  \
count  1743.000000  1743.000000  1.743000e+03  1743.000000  1743.000000  ...
mean      0.000036     0.000090 -8.879694e-05     0.000009    -0.000045  ...
std       0.001944     0.007818  1.175867e-02     0.001575     0.009146  ...
min      -0.007950    -0.053584 -5.734728e-02    -0.009679    -0.072877  ...
25%      -0.000578    -0.001563 -1.453365e-03    -0.000274    -0.002162  ...
50%      -0.000005    -0.000055  4.100000e-07     0.000003     0.000097  ...
75%       0.000513     0.001556  1.574930e-03     0.000227     0.002672  ...
max       0.012589     0.069779  5.529730e-02     0.010286     0.046357  ...

                23           24           25           26           27  \
count  1743.000000  1743.000000  1743.000000  1743.000000  1743.000000
mean     -0.000020     0.000002     0.009802     0.012056     0.008406
std       0.002832     0.000401     0.013098     0.013546     0.011454
min      -0.025803    -0.002817     0.000027     0.000055     0.000032
25%      -0.000467    -0.000072     0.000910     0.001843     0.000825
50%      -0.000006     0.000002     0.003859     0.008161     0.003366
75%       0.000389     0.000093     0.013927     0.017983     0.011613
max       0.062295     0.004936     0.082199     0.154135     0.076566

                28            29           30           31           32
count  1743.000000  1.743000e+03  1743.000000  1743.000000  1743.000000
mean      0.009963  2.065274e-03     0.002529     0.001739     0.001945
std       0.011888  3.018884e-03     0.003858     0.002522     0.003097
min       0.000055  9.400000e-07     0.000003     0.000002     0.000004
25%       0.001313  1.524150e-04     0.000279     0.000143     0.000229
50%       0.005984  7.123900e-04     0.001290     0.000670     0.000978
75%       0.014174  2.800270e-03     0.003508     0.002418     0.002604
max       0.124277  3.080954e-02     0.092324     0.021177     0.073545

[8 rows x 32 columns]

In [313]:

null_values_in_columns = new_testing_data.isnull().any()
print(null_values_in_columns)

1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
dtype: bool

In [336]:
list_of_dataframes = [df_2,  df_5, df_7,  df_9,  df_11, df_13]
# concatenated_df = pd.concat(list_of_dataframes, ignore_index=True)
concatenated_df = pd.concat(list_of_dataframes, axis=0, ignore_index=True)

In [337]:
concatenated_df.shape

(8613, 33)

In [338]:
concatenated_df

,1,2,3,4,5,6,7,8,9,10,...,24,25,26,27,28,29,30,31,32,Phase
0,-0.005009,-0.000964,0.000573,0.008623,0.005667,0.001302,-0.000631,0.000130,-0.000048,0.007762,...,1.880800e-04,0.005133,0.010400,0.000646,0.007871,0.004631,0.000963,0.000092,0.000438,D
1,0.004905,0.001209,-0.000649,0.004737,0.003166,0.000819,-0.000572,-0.000015,0.000023,0.002706,...,-7.500000e-07,0.005093,0.005756,0.000573,0.003459,0.000730,0.000332,0.000012,0.000433,D
2,-0.002393,-0.000216,0.000136,0.003028,0.001212,0.000336,-0.000449,0.000017,0.000047,0.002868,...,-3.920000e-05,0.002406,0.003279,0.000452,0.003261,0.002412,0.000852,0.000042,0.000202,D
3,-0.001394,-0.000242,0.000056,0.001182,0.000575,0.000225,-0.000479,-0.000050,0.000104,0.001171,...,-3.184000e-05,0.001416,0.001334,0.000493,0.001358,0.000313,0.000611,0.000029,0.000596,D
4,-0.000156,-0.000004,0.000023,0.001585,0.000630,0.000094,-0.000303,0.000097,0.000065,0.001579,...,-2.015000e-05,0.000158,0.001709,0.000325,0.001713,0.000203,0.000069,0.000038,0.000069,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8608,-0.003709,-0.006168,0.000786,-0.000155,0.001088,-0.000144,-0.003815,-0.004658,0.000656,0.000060,...,-9.400000e-07,0.007240,0.001109,0.006056,0.000173,0.001976,0.000137,0.001575,0.000051,D
8609,-0.000727,0.001536,-0.000211,0.000700,-0.000975,0.000067,-0.001147,0.000177,0.000008,0.000423,...,1.234000e-05,0.001712,0.001202,0.001160,0.000515,0.002600,0.000701,0.001738,0.000124,D
8610,0.003074,0.007870,-0.000962,0.000526,-0.000779,0.000090,0.002786,0.005035,-0.000606,0.000413,...,2.327000e-05,0.008504,0.000944,0.005786,0.000431,0.002007,0.000071,0.001697,0.000112,D
8611,0.003297,0.008467,-0.001035,0.000578,-0.000740,0.000101,0.002947,0.005385,-0.000652,0.000580,...,1.541000e-05,0.009145,0.000944,0.006173,0.000699,0.000229,0.000023,0.000139,0.000113,D
8612,0.000204,-0.000040,0.000058,0.000586,-0.000619,0.000087,0.000229,0.000003,0.000061,0.000644,...,3.200000e-07,0.000216,0.000857,0.000237,0.000808,0.002763,0.000037,0.001840,0.000036,D

In [339]:
concatenated_df.isnull().any()

1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
30       False
31       False
32       False
Phase    False
dtype: bool

In [340]:
X = concatenated_df.iloc[:, :-1]
y = concatenated_df.iloc[:, -1]

In [341]:
# Encode categorical target variable (y)
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Split the data into training and testing sets

In [342]:
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

In [343]:
# Initialize and train the model
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [345]:
# Make predictions on the testing data
y_pred = model.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.43

In [350]:
X_test = new_testing_data
y_test = sample_sub_df.iloc[:, -1]  # Assuming target variable is in the last column

# Encode categorical target variable (y_test) using the same label encoder
y_test_encoded = label_encoder.transform(y_test)

# Make predictions on the testing data using the trained model
y_pred_test = model.predict(X_test)

In [351]:
accuracy_test = accuracy_score(y_test_encoded, y_pred_test)
print(f"Accuracy on testing data: {accuracy_test:.2f}")

Accuracy on testing data: 0.56

In [316]:
data_2 = {'Phase': ['D', 'P', 'S', 'H', 'R']}
df_b = pd.DataFrame(data_2)


label_encoder = LabelEncoder()


df_b['Phase_encoded'] = label_encoder.fit_transform(df_b['Phase'])
np.save('Phase_encoded.npy', label_encoder.classes_)

concatenated_df = concatenated_df.drop(columns=['Phase'])


concatenated_df['Phase_encoded'] = df_b['Phase_encoded']


print(concatenated_df)

             1         2         3         4         5         6         7  \
0    -0.005009 -0.000964  0.000573  0.008623  0.005667  0.001302 -0.000631
1     0.004905  0.001209 -0.000649  0.004737  0.003166  0.000819 -0.000572
2    -0.002393 -0.000216  0.000136  0.003028  0.001212  0.000336 -0.000449
3    -0.001394 -0.000242  0.000056  0.001182  0.000575  0.000225 -0.000479
4    -0.000156 -0.000004  0.000023  0.001585  0.000630  0.000094 -0.000303
...        ...       ...       ...       ...       ...       ...       ...
8608 -0.003709 -0.006168  0.000786 -0.000155  0.001088 -0.000144 -0.003815
8609 -0.000727  0.001536 -0.000211  0.000700 -0.000975  0.000067 -0.001147
8610  0.003074  0.007870 -0.000962  0.000526 -0.000779  0.000090  0.002786
8611  0.003297  0.008467 -0.001035  0.000578 -0.000740  0.000101  0.002947
8612  0.000204 -0.000040  0.000058  0.000586 -0.000619  0.000087  0.000229

             8         9        10  ...            24        25        26  \
0     0.000130 -0.000048  0.007762  ...  1.880800e-04  0.005133  0.010400
1    -0.000015  0.000023  0.002706  ... -7.500000e-07  0.005093  0.005756
2     0.000017  0.000047  0.002868  ... -3.920000e-05  0.002406  0.003279
3    -0.000050  0.000104  0.001171  ... -3.184000e-05  0.001416  0.001334
4     0.000097  0.000065  0.001579  ... -2.015000e-05  0.000158  0.001709
...        ...       ...       ...  ...           ...       ...       ...
8608 -0.004658  0.000656  0.000060  ... -9.400000e-07  0.007240  0.001109
8609  0.000177  0.000008  0.000423  ...  1.234000e-05  0.001712  0.001202
8610  0.005035 -0.000606  0.000413  ...  2.327000e-05  0.008504  0.000944
8611  0.005385 -0.000652  0.000580  ...  1.541000e-05  0.009145  0.000944
8612  0.000003  0.000061  0.000644  ...  3.200000e-07  0.000216  0.000857

            27        28        29        30        31        32  \
0     0.000646  0.007871  0.004631  0.000963  0.000092  0.000438
1     0.000573  0.003459  0.000730  0.000332  0.000012  0.000433
2     0.000452  0.003261  0.002412  0.000852  0.000042  0.000202
3     0.000493  0.001358  0.000313  0.000611  0.000029  0.000596
4     0.000325  0.001713  0.000203  0.000069  0.000038  0.000069
...        ...       ...       ...       ...       ...       ...
8608  0.006056  0.000173  0.001976  0.000137  0.001575  0.000051
8609  0.001160  0.000515  0.002600  0.000701  0.001738  0.000124
8610  0.005786  0.000431  0.002007  0.000071  0.001697  0.000112
8611  0.006173  0.000699  0.000229  0.000023  0.000139  0.000113
8612  0.000237  0.000808  0.002763  0.000037  0.001840  0.000036

      Phase_encoded
0               0.0
1               2.0
2               4.0
3               1.0
4               3.0
...             ...
8608            NaN
8609            NaN
8610            NaN
8611            NaN
8612            NaN

[8613 rows x 33 columns]

In [324]:
#numeric_columns = concatenated_df.select_dtypes(include=[np.number])
#concatenated_df[numeric_columns.columns] = numeric_columns.fillna(numeric_columns.median())

In [325]:
null_columns = concatenated_df.isnull().any() 
print(null_columns)

1                False
2                False
3                False
4                False
5                False
6                False
7                False
8                False
9                False
10               False
11               False
12               False
13               False
14               False
15               False
16               False
17               False
18               False
19               False
20               False
21               False
22               False
23               False
24               False
25               False
26               False
27               False
28               False
29               False
30               False
31               False
32               False
Phase_encoded    False
dtype: bool

In [319]:
concatenated_df.columns

Index(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13',
       '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25',
       '26', '27', '28', '29', '30', '31', '32', 'Phase_encoded'],
      dtype='object')

In [320]:
X = concatenated_df.drop(columns=['Phase_encoded'])
y = concatenated_df['Phase_encoded']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
scaler = MaxAbsScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [322]:
model = LogisticRegression()

model.fit(X_train, y_train)
predictions = model.predict(X_test)
scores = cross_val_score(model, X_train, y_train, cv=5)

C:\Users\Archi\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_split.py:725: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(

In [323]:
accuracy = accuracy_score(y_test, predictions)
print(f"Accuracy: {accuracy:.2f}")
average_accuracy = scores.mean()
std_accuracy = scores.std()

print(f"Average Accuracy: {average_accuracy:.2f}")
print(f"Standard Deviation: {std_accuracy:.2f}")

Accuracy: 1.00
Average Accuracy: 1.00
Standard Deviation: 0.00

In [302]:
joblib.dump(model, 'Archi_1.pkl')

['Archi_1.pkl']

In [303]:
predictions

array([2., 2., 2., ..., 2., 2., 2.])

In [304]:
# loaded_model = joblib.load('Archi_1.pkl')

X_new_test = new_testing_data[['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32']]
y_pred_encoded = loaded_model.predict(X_new_test)

# X_test_scaled = scaler.transform(X_new_test)

phase_encoded = np.load('Phase_encoded.npy', allow_pickle=True)
y_pred_encoded = y_pred_encoded.astype(int)


y_pred_original = [phase_encoded[pred] for pred in y_pred_encoded]

new_testing_data['Phase_original'] = y_pred_original

new_testing_data.to_csv('predictions.csv', index=False)

In [305]:

y_test = new_testing_data['Phase_original']
accuracy = accuracy_score(y_pred_encoded, y_pred_original)
print(f"Accuracy:, {accuracy:.2f}")

Accuracy:, 0.00